import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { readFile, readdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

const out = process.argv[2];
assert(['dist', 'dist-acceptance'].includes(out), 'Specify dist or dist-acceptance after a Vite build');
const hash = (bytes) => createHash('sha256').update(bytes).digest('hex');
const json = async (file) => JSON.parse(await readFile(file, 'utf8'));
async function files(root) {
  const result = [];
  for (const entry of await readdir(root, { withFileTypes: true })) {
    const name = path.posix.join(root, entry.name);
    if (entry.isDirectory()) result.push(...await files(name));
    else if (entry.isFile()) result.push(name);
  }
  return result.sort();
}
const packageName = (module) => module.split('/').slice(0, module.startsWith('@') ? 2 : 1).join('/');
const modules = await json('artifacts/bundle-modules.json');
const evidence = new Map();
function record(name, reason) {
  if (!evidence.has(name)) evidence.set(name, new Set());
  evidence.get(name).add(reason);
}
for (const module of modules) record(packageName(module), 'Rendered application chunk module');
// The companion unminified distribution provides source labels for the prebuilt workers.
// This is package provenance, not a claim that the current lock version built those workers.
for (const directory of ['Workers', 'ThirdParty']) {
  for (const file of await files(`node_modules/cesium/Build/CesiumUnminified/${directory}`)) {
    if (!file.endsWith('.js')) continue;
    for (const match of (await readFile(file, 'utf8')).matchAll(/^\/\/ node_modules\/(.+)$/gm)) record(packageName(match[1]), 'Cesium companion unminified worker source label (prebuilt version may differ)');
  }
}
record('@zip.js/zip.js', 'Copied ThirdParty zip worker/WASM; Cesium metadata says 2.9.0, installed package differs');
const lock = await json('package-lock.json');
const sections = ['# Third-party licenses and notices\n\nGenerated by scripts/distribution_licenses.mjs. Keep this file with the distribution.\nApplication code is MIT; these terms do not license the population, terrain, imagery or building data.\nCesium source files are not locally patched; application imports are bundled/minified by Vite, and Cesium static assets are copied byte-for-byte.\nApache-2.0 is the selected DOMPurify alternative.\nThe full Cesium license/attribution text below is intentionally retained, including notices for some upstream examples not shipped here.\nSee THIRD_PARTY_PROVENANCE.json and docs/security-verification.md for scope and unresolved prebuilt-binary/asset provenance.\n'];
const packages = [];
for (const [name, reasons] of [...evidence].sort(([a], [b]) => a.localeCompare(b))) {
  const root = `node_modules/${name}`;
  const pkg = await json(`${root}/package.json`);
  assert.equal(pkg.version, lock.packages[root]?.version, `${name}: installed/lock mismatch`);
  const licenseFiles = (await files(root)).filter((file) => /^(licen[sc]e|notice|copying|copyright)(?:[.\-_]|$)/i.test(path.basename(file)) && !file.includes('/node_modules/', 13) && !file.endsWith('LICENSE-MPL'));
  sections.push(`\n## ${name} ${pkg.version}\n\nEvidence: ${[...reasons].join('; ')}.\nPackage metadata license (not a substitute for source terms): ${pkg.license}.\n`);
  for (const file of licenseFiles) sections.push(`\n### ${file}\n\n${await readFile(file, 'utf8')}\n`);
  if (!licenseFiles.length) sections.push('\nNo standalone license file in installed package. See full Cesium license and supplemental source notices below.\n');
  packages.push({ name, version: pkg.version, metadataLicense: pkg.license, reasons: [...reasons], licenseFiles, integrity: lock.packages[root].integrity });
}
// Preserve actual source notices where npm's metadata is incomplete or misleading.
for (const file of ['node_modules/mersenne-twister/src/mersenne-twister.js', 'node_modules/urijs/src/punycode.js', 'node_modules/lerc/LercDecode.js']) {
  const source = await readFile(file, 'utf8');
  const comments = [...source.matchAll(/\/\*[\s\S]*?\*\//g)].map(([comment]) => comment).filter((comment) => /copyright|license|redistribution/i.test(comment));
  sections.push(`\n## Source notices: ${file}\n\n${comments.join('\n\n')}\n`);
}
const pakoMap = await json('node_modules/pako/dist/browser/pako_inflate.esm.min.mjs.map');
const zlibNotices = [...new Set(pakoMap.sourcesContent.map((source) => source?.match(/^(?:\/\/[^\n]*\n)+/)?.[0]).filter((notice) => notice?.includes('This software is provided')))];
assert(zlibNotices.length > 0, 'Missing pako zlib source notices');
sections.push(`\n## Pako bundled zlib source notices (installed source map, not distributed code)\n\n${zlibNotices.join('\n')}\n`);
for (const source of await json('docs/license-sources/sources.json')) assert.equal(hash(await readFile(`docs/license-sources/${source.file}`)), source.sha256, `Supplemental license changed: ${source.file}`);
for (const file of await files('docs/license-sources')) sections.push(`\n## Supplemental upstream material: ${file}\n\n${await readFile(file, 'utf8')}\n`);
const excludedAssets = await json('scripts/cesium-excluded-assets.json');
assert.equal(new Set(excludedAssets).size, 31, 'Exactly 31 reviewed exclusions required');
const cesiumRoot = 'node_modules/cesium/Build/Cesium';
const upstreamAssets = (await Promise.all(['Workers', 'Assets', 'ThirdParty', 'Widgets'].map((directory) => files(`${cesiumRoot}/${directory}`)))).flat().map((file) => file.slice(cesiumRoot.length + 1));
for (const file of excludedAssets) assert(upstreamAssets.includes(file), `Excluded upstream asset missing: ${file}`);
const expectedAssets = upstreamAssets.filter((file) => !excludedAssets.includes(file)).sort();
const actualAssets = (await files(`${out}/cesium`)).map((file) => file.slice(`${out}/cesium/`.length));
assert.deepEqual(actualAssets, expectedAssets, 'Cesium distribution must exclude only the 31 reviewed images');
const embeddedComponents = [await json('docs/license-sources/spz-loader-core-0.3.1-provenance.json')];
const spzLicense = await readFile('docs/license-sources/niantic-spz-LICENSE.txt', 'utf8');
assert(sections.join('\n').includes(spzLicense) && spzLicense.includes('Copyright (c) 2024 Niantic Labs'), 'Missing embedded SPZ MIT notice');
const notice = await readFile(`${out}/NOTICE.txt`, 'utf8');
assert(notice.includes('NASA/Goddard Space Flight Center Scientific Visualization Studio'), 'Missing precise NASA sky credit');
const assets = [];
for (const file of await files(`${out}/cesium`)) {
  const relative = file.slice(out.length + '/cesium/'.length);
  const source = `node_modules/cesium/Build/Cesium/${relative}`;
  const bytes = await readFile(file);
  assert.deepEqual(bytes, await readFile(source), `Copied asset changed: ${relative}`);
  assets.push({ path: `cesium/${relative}`, source, bytes: bytes.length, sha256: hash(bytes) });
}
const notices = sections.join('\n');
const provenance = JSON.stringify({ schemaVersion: 1, lockSha256: hash(await readFile('package-lock.json')), packages, embeddedComponents, excludedAssets: excludedAssets.map((file) => `cesium/${file}`), assets, fonts: assets.filter(({ path }) => /\.(woff2?|ttf|otf|eot)$/i.test(path)), limitations: ['Prebuilt worker source labels do not establish exact dependency versions. Cesium ThirdParty.json is incomplete/stale; not treated as a full SBOM.', 'Rust/WASM source-to-binary reproducibility and the complete linked dependency graph were not established. See supplemental notes.', 'Cesium supplies attribution for textures/icons; exact revisions and provider-thumbnail redistribution rights are not independently established.'] }, null, 2) + '\n';
for (const directory of ['public', out]) {
  await writeFile(`${directory}/THIRD_PARTY_LICENSES.txt`, notices);
  await writeFile(`${directory}/THIRD_PARTY_PROVENANCE.json`, provenance);
}
const all = await files(out);
if (out === 'dist') for (const file of all) {
  const bytes = await readFile(file);
  assert(!bytes.includes(Buffer.from('__mvp')) && !bytes.includes(Buffer.from('__ACCEPTANCE__')), `Acceptance identifier in ${file}`);
}
console.log(`Distribution: ${packages.length} evidenced packages, ${assets.length} byte-identical Cesium assets, ${all.length} files; notices distributed; ${out === 'dist' ? 'production hooks absent' : 'ACCEPTANCE ONLY — do not deploy'}`);
